import SideBar from "@/components/SideBar";

export const metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

export default function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <SideBar />
      {children}
    </>
  );
}
