import SushiHeader from "@/components/SushiHeader";

export const metadata = {
  title: "Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <SushiHeader title="CART" />
      {children}
    </>
  );
}
