import SideBar from "@/components/SideBar";
import "./globals.scss";
import { Mulish } from "next/font/google";
import SushiFooter from "@/components/SushiFooter";
import Provider from "@/store/provider";
import QueryProvider from "@/store/QueryProvider";

const mulish = Mulish({
  weight: ["800", "600", "400", "300", "200"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sushi Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <SideBar />
        <QueryProvider>
          <Provider>{children}</Provider>
        </QueryProvider>
        <SushiFooter />
      </body>
    </html>
  );
}
